apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-2
  labels:
    app: my-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-2
  template:
    metadata:
      labels:
        app: my-app-2
    spec:
      containers:
      - name: reverse
        image: neetagupta236/simple-reverse-proxy
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
