apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        api: external
    spec:
      containers:
        - image: neetagupta236/udagram-frontend:v4
          name: frontend
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1024Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          ports:
          - containerPort: 80
      restartPolicy: Always     