apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    targetPort: 8080
  selector:
    app: frontend
  type: LoadBalancer
